version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../web/.env

  web:
    image: rustamwho/atr-web:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ../web/.env

  dynamic-tests:
    image: rustamwho/atr-dynamic-testing:latest
    container_name: dynamic-tests
    command: gunicorn --bind 0.0.0.0:6000 manage:app
    ports:
      - "6000:6000"
    restart: always
    depends_on:
      - web

  static-tests:
    image: rustamwho/atr-static-testing:latest
    # in other platforms - Bus error with cdmpyparser
    platform: linux/amd64
    container_name: static-tests
    command: gunicorn --bind 0.0.0.0:6001 manage:app
    ports:
      - "6001:6001"
    restart: always
    depends_on:
      - web

  redis:
    image: redis
    restart: always

  celery:
    restart: always
    build:
      context: ../web
    env_file:
      - ../web/.env
    command: celery -A web worker --loglevel=INFO
    depends_on:
      - web
      - redis

  frontend:
    image: rustamwho/atr-frontend:latest
    volumes:
      - frontend_data:/app/build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html/
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - web
    links:
      - dynamic-tests
      - web

volumes:
  static_value:
  media_value:
  postgres_data:
  frontend_data: