version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../web/.env

  redis:
    image: redis
    restart: always

  web:
    restart: always
    build:
      context: ../web
      dockerfile: Dockerfile
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ../web/.env

  dynamic-tests:
    build:
      context: ../dynamic_tests
      dockerfile: Dockerfile
    container_name: dynamic-tests
    command: gunicorn --bind 0.0.0.0:6000 manage:app
    ports:
      - "6000:6000"
    restart: always
    depends_on:
      - web

  celery:
    restart: always
    build:
      context: ../web
    env_file:
      - ../web/.env
    command: celery -A web worker --loglevel=INFO
    depends_on:
      - web
      - redis


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    links:
      - dynamic-tests
      - web

volumes:
  static_value:
  media_value:
  postgres_data: